### PR TITLE
dynvolc.xml creation

### PR DESCRIPTION
**Pull request by emmdelage**
Hi again,
I've just found "HOW TO CONTRIBUTE"
sorry for my previous pull request.
Cheers,
Emmanuel

### CODE REVIEW

**Comment by rpaciello** [comment]
Hi @emmdelage,
I can't accept the commit because your file isn't a valid XML file. The tool to use for validation is: https://www.freeformatter.com/xml-validator-xsd.html
Please, can you fix the errors and validate it?
Thank you!

**Comment by emmdelage** [comment]
Ok, I believe the dynvolc xml file is valid now.

emmdelage wants to merge 3 commits into epos-eu:master from emmdelage:master 

Please

**Comment by emmdelage** [comment]
Dear Rosanna, I won't be very active for EPOS during the next 3 weeks.
I would like to explain a way to do to my collegues before week-end.
Could you please push my file ? or should I ask a pull request with a new file ?
Emmanuel

**Comment by epos-eu** [comment]
@emmdelage your file was properly merged

**Pull request merged**
