### PR TITLE
Updated fdsn, radon and vpvs

### PR DESCRIPTION
**Pull request by maratumba**

### CODE REVIEW

**Comment by manuelasbarra** [comment]
Please, the new  URL of the web service doesn't work -Service Unavailable
http://toros.boun.edu.tr/nfo_marsite/vpvs/query?
http://toros.boun.edu.tr/nfo_marsite/radon/query?
Could you check?

**Comment by maratumba** [comment]
Should be working now.

---
Yaman Özakın *<:^)
PhD - Geophysics
earth.usc.edu/~ozakin/
Kandilli Observatory Earthquake and Research Institute

**Comment by manuelasbarra** [comment]
Now It's ok!

**Comment by manuelasbarra** [comment]
Now the URL of the web service in this file
EPOS-DCAT-AP_WP09_KOERI_event.xml

doesn't work -Service Unavailable

http://toros.boun.edu.tr/fdsnws/nfo_marsite/event/1/query?
Could you check it?
Manuela

-----------------------------------------------------
  Dott.ssa MANUELA SBARRA
  INGV - ISTITUTO NAZIONALE GEOFISICA E VULCANOLOGIA
  U.F.  C.S.I. Centro Servizi Informativi
  Via di Vigna Murata 605
  00143 Rome, Italy
  Tel. 0651860360
-----------------------------------------------------

2017-09-18 20:51 GMT+02:00 Yaman Ozakin <notifications@github.com>:

**Comment by maratumba** [comment]
Should be operational now. Someone had shutdown the machine apparently.
Sorry for the inconvenience.

---
Yaman Özakın *<:^)
PhD - Geophysics
earth.usc.edu/~ozakin/
Kandilli Observatory Earthquake and Research Institute

**Comment by manuelasbarra** [comment]
Thank you, now the web service is up and ok.
But could you suggest me a query with parameters to test it consistency?



-----------------------------------------------------
  Dott.ssa MANUELA SBARRA
  INGV - ISTITUTO NAZIONALE GEOFISICA E VULCANOLOGIA
  U.F.  C.S.I. Centro Servizi Informativi
  Via di Vigna Murata 605
  00143 Rome, Italy
  Tel. 0651860360
-----------------------------------------------------

2017-09-19 13:20 GMT+02:00 Yaman Ozakin <notifications@github.com>:

**Comment by maratumba** [comment]
This is a very basic query I hope will help:
http://toros.boun.edu.tr/fdsnws/event/1/query?nodata=404

We are still uploading data so there won't be any real data for a day or
two.

---
Yaman Özakın *<:^)
PhD - Geophysics
earth.usc.edu/~ozakin/
Kandilli Observatory Earthquake and Research Institute

**Comment by manuelasbarra** [comment]
Thank you for your clarification and for your example.

We have a deadline for tomorrow for TRA,
so if you can not update data by tomorrow
probably I can't  include it now.

Best regards
Manuela



-----------------------------------------------------
  Dott.ssa MANUELA SBARRA
  INGV - ISTITUTO NAZIONALE GEOFISICA E VULCANOLOGIA
  U.F.  C.S.I. Centro Servizi Informativi
  Via di Vigna Murata 605
  00143 Rome, Italy
  Tel. 0651860360
-----------------------------------------------------

2017-09-19 14:42 GMT+02:00 Yaman Ozakin <notifications@github.com>:

**Comment by maratumba** [comment]
Data is online. You can check with this query:
http://toros.boun.edu.tr/fdsnws/event/1/query?limit=30&nodata=404

---
Yaman Özakın *<:^)
PhD - Geophysics
earth.usc.edu/~ozakin/
Kandilli Observatory Earthquake and Research Institute

**Comment by manuelasbarra** [comment]
Hi Yaman
Your databases in your webservices
http://toros.boun.edu.tr/nfo_marsite/radon/query?
http://toros.boun.edu.tr/nfo_marsite/vpvs/query?

don't work.

Could you check please?

*
http://toros.boun.edu.tr/nfo_marsite/radon/query?minlat=40.5&maxlon=31.0&minlon=28.0&maxlat=41.0&mintime=2012-11-01T00:00:00.000&maxtime=2012-11-02T00:00:00.000

Manuela


-----------------------------------------------------
  Dott.ssa MANUELA SBARRA
  INGV - ISTITUTO NAZIONALE GEOFISICA E VULCANOLOGIA
  U.F.  C.S.I. Centro Servizi Informativi
  Via di Vigna Murata 605
  00143 Rome, Italy
  Tel. 0651860360
-----------------------------------------------------

2017-09-21 0:50 GMT+02:00 Yaman Ozakin <notifications@github.com>:

**Comment by maratumba** [comment]
Should be working now.

---
Yaman Özakın *<:^)
PhD - Geophysics
earth.usc.edu/~ozakin/
Kandilli Observatory Earthquake and Research Institute

**Pull request merged**
