### PR TITLE
BoreholeIndex WFS and EPOS-DCAT-AP

### PR DESCRIPTION
**Pull request by sgrellet**
First try mapping WFS capabilities and DescribeFeatureType to
EPOS-DCAT-AP

### CODE REVIEW

**Comment by rpaciello** [comment]
Sorry, but I can't accept the commit because your file isn't valid. 
Please use this tool to validate it
https://www.freeformatter.com/xml-validator-xsd.html

**Comment by sgrellet** [comment]
The file is valid in XML Spy here.
I just changed the xsi:schemaLocation of EPOS-DCAT-AP.xsd from
xsi:schemaLocation="http://www.epos-ip.org/terms.html https://raw.githubusercontent.com/epos-eu/EPOS-DCAT-AP/master/schemas/EPOS-DCAT-AP.xsd">
to  
xsi:schemaLocation="http://www.epos-ip.org/terms.html ../../schemas/EPOS-DCAT-AP.xsd">
to enable validation on my laptop
Can you update this ?

**Comment by rpaciello** [comment]
Unfortunately this change is not enough to make it valid. 
There are still these mistakes: 
Cvc-datatype-valid.1.2.1: 'TBD : Identifier Of 'Support BRGM' ?' Is Not A Valid Value For 'anyURI'., Line '75', Column '83'.
Cvc-type.3.1.3: The Value 'TBD : Identifier Of 'Support BRGM' ? ' Of Element 'eposap:legalContact' Is Not Valid., Line '75', Column '83'.
Cvc-datatype-valid.1.2.1: 'TBD : Identifier Of 'Support BRGM' ?' Is Not A Valid Value For 'anyURI'., Line '77', Column '90'.
Cvc-type.3.1.3: The Value 'TBD : Identifier Of 'Support BRGM' ?' Of Element 'eposap:financialContact' Is Not Valid., Line '77', Column '90'.

**Comment by sgrellet** [comment]
weird.
I patched this (see attached)

[BoreholeDataIndex_WFS-DCAT-AP.zip](https://github.com/epos-eu/EPOS-DCAT-AP/files/1136356/BoreholeDataIndex_WFS-DCAT-AP.zip)

**Comment by rpaciello** [comment]
Ok. I uploaded your xml file in WP15 folder.

**Pull request closed without merging**
