### PR TITLE
update_WP8-NIEP-20180913

### PR DESCRIPTION
**Pull request by cristianneagoe**

### CODE REVIEW

**Comment by megies** [comment]
Hi @cristianneagoe, I used your file as a template.. just noticed you have family/given name mixed up. cheers!

https://github.com/cristianneagoe/EPOS-DCAT-AP/blob/6e8020c0d98a7f5ae4b3bbe052890693ec39d4df/examples/WP08/WP8-NIEP-20180913.ttl#L37-L38

**Comment by rpaciello** [comment]
@megies 
It would be better use the [example](https://github.com/epos-eu/EPOS-DCAT-AP/blob/EPOS-DCAT-AP-shapes/examples/EPOS-DCAT-AP_example.ttl) as a template.

**Comment by megies** [comment]
> @megies
> It would be better use the [example](https://github.com/epos-eu/EPOS-DCAT-AP/blob/EPOS-DCAT-AP-shapes/examples/EPOS-DCAT-AP_example.ttl) as a template.

Maybe I can change #293 tomorrow..

**Comment by rpaciello** [comment]
@megies 
OK, so I close your pull request [#293](https://github.com/epos-eu/EPOS-DCAT-AP/pull/293)

**Pull request merged**
