### PR TITLE
Update accordinf metadata Quality control

### PR DESCRIPTION
**Pull request by lemarchandarnaud**
Hi
I  also add two new turtle files for tide and tilt data given that they are formated as seismic data. Thus the web services description are similar  to FDSN web service. 
I have opened the link for keywords in the guideline file. Unfortunately  the column "proposed" is empty. I guess we didn't send you enough information about it. Thus I didn't update the list of my keywords !
Otherwise I have tried to respect the guidelines. 
I don't really understand the spatio-temporal information for the Webservice, thus I fill it with the statio-temporal info of the dataset.

### CODE REVIEW

**Comment by rpaciello** [comment]
Your pull request has conflicts and for this reason we made your changes in your files manually. You can see all files updated/added in the GitHub folder.

**Comment by lemarchandarnaud** [comment]
Dear Rossana

Sorry for the conflicts , I  have clear them in my fork and local
repository for the next time.
I  have on comment about the line : dct:title "Seismic waveform :: IPGP";
Why did you keep ":: IPGP" although the guidelines advice not to use
institution name in this field.

See you
arnaud

**Comment by rpaciello** [comment]
Yes, you are right. We just updated dct:title with "Seismic waveform".
Please, check if you need further changes.

**Comment by lemarchandarnaud** [comment]
a- the WP11 is  discussing and working  on working on keywords. I guess I
will     commit new changes about keyword once it is finished.

b- you didn't accept lines:
schema:legalName "French seismologic and geodetic network"@en;
schema:legalName "Institute of Earth Physics of Paris"@en;

I think I have  systematically add the name in  English and in French. I
might misunderstand the guidelines.
Can I keep the two line ? or Must I choose one language , in this case I
had rather keep English.

nothing else for the moment
see you
arnaud

**Pull request closed without merging**
